services:

  couchbase:
    image: couchbase
    ports:
      - 8091-8097:8091-8097
      - 9123:9123
      - 11207:11207
      - 11210:11210
      - 11280:11280
      - 18091-18097:18091-18097
    environment:  
      - CLUSTER_NAME=aisync
      - COUCHBASE_ADMINISTRATOR_USERNAME=admin
      - COUCHBASE_ADMINISTRATOR_PASSWORD=zxc123
      - COUCHBASE_BUCKET=aisync
      - COUCHBASE_BUCKET_RAMSIZE=512
      - COUCHBASE_RBAC_USERNAME=admin
      - COUCHBASE_RBAC_PASSWORD=zxc123
      - COUCHBASE_RAM_SIZE=2048
      - COUCHBASE_INDEX_RAM_SIZE=512
    volumes:
      - './init.sh:/opt/couchbase/init/init.sh'
    entrypoint: [ '' ]
    command: sh -c "/opt/couchbase/init/init.sh"

  sync-gateway:
    image: couchbase/sync-gateway
    depends_on:
      - couchbase
    ports:
      - 4984-4986:4984-4986
    volumes:
      - './config.json:/etc/sync_gateway/config.json'

